package com.xysoft.szhsj.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BenBusService service = new BenBusService();
 * BenBusService portType = service.getBenBusServicePort();
 * portType.getData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BenBusService", targetNamespace = "http://service.BC.mgear.com/", wsdlLocation = "http://194.244.1.205:7021/BenchmarkBusiness/BenBusService?WSDL")
public class BenBusService_Service extends Service {

	private final static URL BENBUSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.xysoft.szhsj.webservice.BenBusService_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.xysoft.szhsj.webservice.BenBusService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://194.244.1.205:7021/BenchmarkBusiness/BenBusService?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://194.244.1.205:7021/BenchmarkBusiness/BenBusService?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BENBUSSERVICE_WSDL_LOCATION = url;
	}

	public BenBusService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BenBusService_Service() {
		super(BENBUSSERVICE_WSDL_LOCATION, new QName(
				"http://service.BC.mgear.com/", "BenBusService"));
	}

	/**
	 * 
	 * @return returns BenBusService
	 */
	@WebEndpoint(name = "BenBusServicePort")
	public BenBusService getBenBusServicePort() {
		return super.getPort(new QName("http://service.BC.mgear.com/",
				"BenBusServicePort"), BenBusService.class);
	}

}
