package com.xysoft.szhsj.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BenBusService", targetNamespace = "http://service.BC.mgear.com/")
public interface BenBusService {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getData", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.GetData")
	@ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.GetDataResponse")
	public String getData(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setData", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.SetData")
	@ResponseWrapper(localName = "setDataResponse", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.SetDataResponse")
	public String setData(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "upFile", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.UpFile")
	@ResponseWrapper(localName = "upFileResponse", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.UpFileResponse")
	public String upFile(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") byte[] arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteFile", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.DeleteFile")
	@ResponseWrapper(localName = "deleteFileResponse", targetNamespace = "http://service.BC.mgear.com/", className = "com.xysoft.szhsj.webservice.DeleteFileResponse")
	public String deleteFile(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
